apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "automationengine.fullname" . }}
  labels:
    {{- include "automationengine.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  progressDeadlineSeconds: 1200
  selector:
    matchLabels:
      {{- include "automationengine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "automationengine.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "automationengine.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command: 
            - powershell.exe
            - -NoLogo
            - -NoProfile
            - -File
            - C:\tools\entrypoints\worker\Development.ps1
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.tag }}"
          env:
            - name: SITECORE_LICENSE
              valueFrom:
                secretKeyRef:
                  name: sitecore-license
                  key: sitecore-license.txt
            # - name: SITECORE_LICENSE_LOCATION
            #   value: "C:\\license\\license.xml"
            - name: SITECORE_CONNECTIONSTRINGS_XCONNECT.COLLECTION
              value: "http://{{ include "xconnect.fullName" . }}"
            
            - name: SITECORE_CONNECTIONSTRINGS_XDB.MARKETINGAUTOMATION
              value: "Data Source={{ include "sql.fullName" . }};Database=Sitecore.MarketingAutomation;User ID=sa;Password={{ .Values.global.sqlSaPassword }}"
            
            - name: SITECORE_CONNECTIONSTRINGS_XDB.REFERENCEDATA
              value: "Data Source={{ include "sql.fullName" . }};Database=Sitecore.ReferenceData;User ID=sa;Password={{ .Values.global.sqlSaPassword }}"
            
            - name: SITECORE_CONNECTIONSTRINGS_MESSAGING
              value: "Data Source={{ include "sql.fullName" . }};Database=Sitecore.Messaging;User ID=sa;Password={{ .Values.global.sqlSaPassword }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: license
            mountPath: "C:/license"
            readOnly: true
      volumes:
      - name: license
        secret:
          secretName: {{ .Values.global.licenseFileSecretName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
