replicaCount: 1

image:
  tag:
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

solrServiceNameOverride: ""
sqlServiceNameOverride: ""

licenseFileSecretName:
sqlSaPassword:
adminPassword:
telerikEncryptionKey:
unicornSharedSecret:

cmp:
  contenthub:
  servicebussubscription:
  servicebusentitypathin:
  servicebusentitypathout:
   

sfmc: "client id=;client secret=;auth endpoint=https://example.com;rest endpoint=https://example.com;soap endpoint=https://example.com"

entrypoint:
  sitecoreLogEnabled: "true"
  iisAccessLogEnabled: "false"
  iisErrorLogEnabled: "false"

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []
  
resources:
  limits:
    cpu: 2
    memory: 3Gi
  requests:
    cpu: 1
    memory: 2Gi

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 60

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 60

nodeSelector:
  kubernetes.io/os: windows

tolerations: []

affinity: {}

