Registry=
Domain=yxz
Namespace=abc
UserPassword=abc
AdminUserName=adminabc
disable_admin=false
Tag=latest

  helm install sitecoreninethree sitecore930-xp --namespace $Namespace \
  --set sql.user.password="$UserPassword"   \
  --set sql.admin.username="$AdminUserName"  \
  --set sql.admin.password="$UserPassword"  \
  --set sql.admin.disable.default="$disable_admin"  \
  --set cm.dam.url="bogus" \
  --set cm.ingress.enabled=false \
  --set cm.ingress.annotations."kubernetes\.io/ingress\.class"="nginx" \
  --set cm.ingress.annotations."nginx\.ingress\.kubernetes\.io/proxy-connect-timeout"="60s" \
  --set cm.ingress.annotations."nginx\.ingress\.kubernetes\.io/proxy-send-timeout"="60s" \
  --set cm.ingress.annotations."nginx\.ingress\.kubernetes\.io/proxy-read-timeout"="60s" \
  --set cm.ingress.hosts[0].host="$Namespace-cm.$Domain.com" \
  --set cm.ingress.hosts[0].paths[0]="/" \
  --set cm.ingress.tls[0].hosts[0]="$Namespace-cm.$Domain.com" \
  --set cm.ingress.tls[0].secretName="$Namespace-ingress-tls" \
  --set cd.ingress.enabled=false \
  --set cd.ingress.annotations."kubernetes\.io/ingress\.class"="nginx" \
  --set cd.ingress.annotations."nginx\.ingress\.kubernetes\.io/affinity"="cookie" \
  --set cd.ingress.hosts[0].host="$Namespace.$Domain.com" \
  --set cd.ingress.hosts[0].paths[0]="/" \
  --set cd.ingress.tls[0].hosts[0]="$Namespace.$Domain.com" \
  --set cd.ingress.tls[0].secretName="$Namespace-ingress-tls" \
  --set sql.image.tag="${Registry}sitecore-xp-sqldev-ps:9.3.0-windowsservercore-ltsc2019" \
  --set solr.image.tag="${Registry}sitecore-xp-solr:9.3.0-nanoserver-1809" \
  --set cm.image.tag="${Registry}sitecore-xp-ps-standalone:9.3.0-windowsservercore-ltsc2019" \
  --set cd.image.tag="${Registry}sitecore-xp-ps-cd:9.3.0-windowsservercore-ltsc2019" \
  --set ps.image.tag="${Registry}sitecore-ps:9.3.0-windowsservercore-ltsc2019" \
  --set xconnect.image.tag="${Registry}sitecore-xp-xconnect:9.3.0-windowsservercore-ltsc2019" \
  --set indexworker.image.tag="${Registry}sitecore-xp-xconnect-indexworker:9.3.0-windowsservercore-ltsc2019" \
  --set automationengine.image.tag="${Registry}sitecore-xp-xconnect-automationengine:9.3.0-windowsservercore-ltsc2019" \
  --set identity.secret="abc" \
  --set identity.certificate="abc" \
  --set identity.certificatepassword="abc" \
  --set sitecore.license="abc" \
  --set teleriken.cryptionkey="abc" \
  --set global.sqlSaPassword="abc" \
  --set global.telerikEncryptionKey="abc" \
  --set tls.crt="abc" \
  --set tls.key="abc" \