apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cd.secretName" . }}
  labels:
    {{- include "cd.labels" . | nindent 4 }}
type: Opaque
data:
  telerik_encryption_key: {{ .Values.global.telerikEncryptionKey | b64enc | quote }}
