image:
  tag:
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 1433

edition: Express
sqlSaPassword:

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi

volumeClaim:
  storageClassName: ""
  storageSize: ""
  accessModes: []

nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity: {}
