apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ps.fullname" . }}
  labels:
    {{- include "ps.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  progressDeadlineSeconds: 1200
  selector:
    matchLabels:
      {{- include "ps.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ps.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "ps.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}	
          env:
            - name: SITECORE_LICENSE_LOCATION
              value: "C:\\license\\license.xml"
            - name: CONN_STRING_CORE
              value: "Data Source={{ include "sql.fullName" . }};Initial Catalog=Sitecore.Core;User ID=sa;Password={{ .Values.global.sqlSaPassword }}"
            - name: CONN_STRING_MASTER
              value: "Data Source={{ include "sql.fullName" . }};Initial Catalog=Sitecore.Master;User ID=sa;Password={{ .Values.global.sqlSaPassword }}"
            - name: CONN_STRING_WEB
              value: "Data Source={{ include "sql.fullName" . }};Initial Catalog=Sitecore.Web;User ID=sa;Password={{ .Values.global.sqlSaPassword }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{  .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: license
            mountPath: "C:/license"
            readOnly: true
      volumes:
      - name: license
        secret:
          secretName: {{ .Values.global.licenseFileSecretName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
