image:
  tag:
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 1433

edition: Express
sqlSaPassword:

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1
    memory: 2Gi

volumeClaim:
  storageClassName: ""
  storageSize: ""
  accessModes: []

nodeSelector: 
  kubernetes.io/os: windows

tolerations: []

affinity: {}

user:
  password: b

# alias admin
admin:
  username: 
  password: b
  disable:
    default: 'FALSE'

dam:
  url: bogus
