apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sql.secretName" . }}
  labels:
    {{- include "sql.labels" . | nindent 4 }}
type: Opaque
data:
  sql_sa_password: {{ .Values.global.sqlSaPassword | b64enc | quote }}
